grpc:
  server:
    port: 9000

spring:
  application:
    name: GRPC-DEMO
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/seeder?useSSL=false&characterEncoding=latin1}
    username: ${DB_USERNAME:springstudent}
    password: ${DB_PASSWORD:Spring@123}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
