grpc:
  server:
    port: 9000

spring:
  application:
    name: GRPC-DEMO
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://sql6.freesqldatabase.com:3306/sql6584177?useSSL=false&characterEncoding=latin1}
    username: ${DB_USERNAME:sql6584177}
    password: ${DB_PASSWORD:tTcgyevDvi}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
